### ISSUE TITLE
Cache Rust on CI

### ISSUE THREAD

**Issue by eitsupi** [eitsupi/prqlr#129]
Like:

```yml
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: build
          workspaces: ./src/rust/
```
